# Q1. What are the benefits of the built-in array package, if any?


# Q2. What are some of the array package&#39;s limitations?



The array package in Python offers benefits in terms of memory efficiency and performance for specific use cases, it also has some limitations compared to Python lists:
1. Limited Data Types
2. Fixed Size
3. Limited Functionality
4. Less Commonly Used
5. Lack of Slicing and Indexing Flexibility
6. Inefficiency for Non-Numerical Data
7. Potential Complexity for Beginners


# Q3. Describe the main differences between the array and numpy packages.



# Q4. Explain the distinctions between the empty, ones, and zeros functions.



# Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?



# Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?



In [6]:
# Example :
import numpy as np
a=np.arange(9).reshape(3,3)
print(a)
print()
print(a+1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?



In [7]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
a+=1
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a*=2
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?



In [11]:
import numpy as np
name = np.array(['ram', 'mohan', 'shiva'])
name

array(['ram', 'mohan', 'shiva'], dtype='<U5')

In [13]:
name[name=='ram']='undertaker'
print(name)

['under' 'mohan' 'shiva']


# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?



In [14]:
# Example is as follows :

a1=a
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
a2=a+2
a2

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [16]:
a1+a2

array([[ 6, 10, 14],
       [18, 22, 26],
       [30, 34, 38]])

In [17]:
a1*a2

array([[  8,  24,  48],
       [ 80, 120, 168],
       [224, 288, 360]])

In [19]:
a1*a2.reshape(9,1)

ValueError: operands could not be broadcast together with shapes (3,3) (9,1) 

# Q10. What is the best way to use a Boolean array to mask another array?



In [29]:
y = np.array([True,True,False,True])          
x = np.array([1,2,3,4])         
m = np.ma.masked_where(x>2,y)  
print(list(m))
print(m.ndim)

[True, True, masked, masked]
1


# Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.



In [ ]:
# 1) Using math module :
import math
N = 1
avg=a
total=N
x=[1,2]
SD=math.sqrt((1-a)**2+(2-a)**2/N)

In [33]:
# 2) Using Numpy Array package
import numpy as np
SD=np.std(x)

In [ ]:
# 3) General calculation without using any package
SD= (((1-avg)**2 + (2-avg)**2)/N)**1/2

# 12. What is the dimensionality of a Boolean mask-generated array?